gui:
  nerdFontsVersion: "3"
  useHunkModeInStagingView: true
theme:
  activeBorderColor:
    - '#b4befe'
    - bold
  inactiveBorderColor:
    - '#a6adc8'
  optionsTextColor:
    - '#89b4fa'
  selectedLineBgColor:
    - '#313244'
  cherryPickedCommitBgColor:
    - '#45475a'
  cherryPickedCommitFgColor:
    - '#b4befe'
  unstagedChangesColor:
    - '#f38ba8'
  defaultFgColor:
    - '#cdd6f4'
  searchingActiveBorderColor:
    - '#f9e2af'

authorColors:
  '*': '#b4befe'

# Create pull request command opens a URL with incorrect escaping #3064
# https://github.com/jesseduffield/lazygit/issues/3064
os:
  openLink: open "$(echo "{{link}}" | sed 's/%2F/\//g')"
